# Generated by Django 5.2 on 2025-04-21 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_date_joined"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="team_leader",
            field=models.ForeignKey(
                blank=True,
                help_text="If the user is part of a team, link to their Team Leader.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="team_members",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("GENERAL", "General"),
                    ("EMPLOYEE", "Employee"),
                    ("OWNER", "Owner"),
                    ("TEAM_LEADER", "Team Leader"),
                ],
                default="GENERAL",
                max_length=20,
            ),
        ),
    ]
