--
-- PostgreSQL database dump
--

-- Dumped from database version 16.8 (Ubuntu 16.8-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 16.8 (Ubuntu 16.8-0ubuntu0.24.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


--ALTER TABLE public.auth_group OWNER TO postgres;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: authtoken_token; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.authtoken_token (
    key character varying(40) NOT NULL,
    created timestamp with time zone NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.authtoken_token OWNER TO postgres;

--
-- Name: bookings_booking; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.bookings_booking (
    id bigint NOT NULL,
    start_time timestamp with time zone NOT NULL,
    end_time timestamp with time zone NOT NULL,
    status character varying(20) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    notes text,
    user_id bigint NOT NULL,
    workspace_id bigint NOT NULL,
    booked_by_id bigint
);


ALTER TABLE public.bookings_booking OWNER TO postgres;

--
-- Name: bookings_booking_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.bookings_booking ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bookings_booking_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bookings_teaminvitation; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.bookings_teaminvitation (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    accepted boolean NOT NULL,
    invitee_id bigint NOT NULL,
    leader_id bigint NOT NULL
);


ALTER TABLE public.bookings_teaminvitation OWNER TO postgres;

--
-- Name: bookings_teaminvitation_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.bookings_teaminvitation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bookings_teaminvitation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- Name: notifications_notification; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.notifications_notification (
    id bigint NOT NULL,
    notification_type character varying(50) NOT NULL,
    message text NOT NULL,
    is_read boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    read_at timestamp with time zone,
    booking_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.notifications_notification OWNER TO postgres;

--
-- Name: notifications_notification_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.notifications_notification ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notifications_notification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: teams_team; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.teams_team (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    leader_id bigint NOT NULL
);


ALTER TABLE public.teams_team OWNER TO postgres;

--
-- Name: teams_team_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.teams_team ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.teams_team_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: teams_team_members; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.teams_team_members (
    id bigint NOT NULL,
    team_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.teams_team_members OWNER TO postgres;

--
-- Name: teams_team_members_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.teams_team_members ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.teams_team_members_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: teams_teaminvitation; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.teams_teaminvitation (
    id bigint NOT NULL,
    accepted boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    recipient_id bigint NOT NULL,
    sender_id bigint NOT NULL,
    team_id bigint NOT NULL
);


ALTER TABLE public.teams_teaminvitation OWNER TO postgres;

--
-- Name: teams_teaminvitation_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.teams_teaminvitation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.teams_teaminvitation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users_user (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    email character varying(254) NOT NULL,
    phone character varying(20) NOT NULL,
    user_type character varying(20) NOT NULL,
    team_leader_id bigint
);


ALTER TABLE public.users_user OWNER TO postgres;

--
-- Name: users_user_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users_user_groups (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.users_user_groups OWNER TO postgres;

--
-- Name: users_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_user_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users_user_user_permissions (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.users_user_user_permissions OWNER TO postgres;

--
-- Name: users_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: workspaces_amenity; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.workspaces_amenity (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    description text NOT NULL,
    icon character varying(50) NOT NULL
);


ALTER TABLE public.workspaces_amenity OWNER TO postgres;

--
-- Name: workspaces_amenity_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.workspaces_amenity ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.workspaces_amenity_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: workspaces_workspace; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.workspaces_workspace (
    id bigint NOT NULL,
    name character varying(200) NOT NULL,
    description text NOT NULL,
    is_available boolean NOT NULL,
    opening_time time without time zone NOT NULL,
    closing_time time without time zone NOT NULL,
    location character varying(255) NOT NULL,
    address text NOT NULL,
    max_capacity integer NOT NULL,
    min_capacity integer NOT NULL,
    price_per_hour numeric(10,2) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    thumbnail character varying(100) NOT NULL,
    owner_id bigint NOT NULL,
    workspace_type_id bigint,
    CONSTRAINT workspaces_workspace_max_capacity_check CHECK ((max_capacity >= 0)),
    CONSTRAINT workspaces_workspace_min_capacity_check CHECK ((min_capacity >= 0))
);


ALTER TABLE public.workspaces_workspace OWNER TO postgres;

--
-- Name: workspaces_workspace_amenities; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.workspaces_workspace_amenities (
    id bigint NOT NULL,
    workspace_id bigint NOT NULL,
    amenity_id bigint NOT NULL
);


ALTER TABLE public.workspaces_workspace_amenities OWNER TO postgres;

--
-- Name: workspaces_workspace_amenities_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.workspaces_workspace_amenities ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.workspaces_workspace_amenities_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: workspaces_workspace_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.workspaces_workspace ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.workspaces_workspace_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: workspaces_workspacetype; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.workspaces_workspacetype (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    description text NOT NULL
);


ALTER TABLE public.workspaces_workspacetype OWNER TO postgres;

--
-- Name: workspaces_workspacetype_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.workspaces_workspacetype ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.workspaces_workspacetype_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
19	Can delete session	5	delete_session
20	Can view session	5	view_session
21	Can add user	6	add_user
22	Can change user	6	change_user
23	Can delete user	6	delete_user
24	Can view user	6	view_user
25	Can add amenity	7	add_amenity
26	Can change amenity	7	change_amenity
27	Can delete amenity	7	delete_amenity
28	Can view amenity	7	view_amenity
29	Can add workspace	8	add_workspace
30	Can change workspace	8	change_workspace
31	Can delete workspace	8	delete_workspace
32	Can view workspace	8	view_workspace
33	Can add workspace type	9	add_workspacetype
34	Can change workspace type	9	change_workspacetype
35	Can delete workspace type	9	delete_workspacetype
36	Can view workspace type	9	view_workspacetype
37	Can add booking	10	add_booking
38	Can change booking	10	change_booking
39	Can delete booking	10	delete_booking
40	Can view booking	10	view_booking
41	Can add Token	11	add_token
42	Can change Token	11	change_token
43	Can delete Token	11	delete_token
44	Can view Token	11	view_token
45	Can add Token	12	add_tokenproxy
46	Can change Token	12	change_tokenproxy
47	Can delete Token	12	delete_tokenproxy
48	Can view Token	12	view_tokenproxy
49	Can add notification	13	add_notification
50	Can change notification	13	change_notification
51	Can delete notification	13	delete_notification
52	Can view notification	13	view_notification
53	Can add team invitation	14	add_teaminvitation
54	Can change team invitation	14	change_teaminvitation
55	Can delete team invitation	14	delete_teaminvitation
56	Can view team invitation	14	view_teaminvitation
57	Can add team	15	add_team
58	Can change team	15	change_team
59	Can delete team	15	delete_team
60	Can view team	15	view_team
61	Can add team invitation	16	add_teaminvitation
62	Can change team invitation	16	change_teaminvitation
63	Can delete team invitation	16	delete_teaminvitation
64	Can view team invitation	16	view_teaminvitation
\.


--
-- Data for Name: authtoken_token; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.authtoken_token (key, created, user_id) FROM stdin;
\.


--
-- Data for Name: bookings_booking; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.bookings_booking (id, start_time, end_time, status, created_at, updated_at, notes, user_id, workspace_id, booked_by_id) FROM stdin;
135	2025-04-22 11:00:00+01	2025-04-22 13:00:00+01	PENDING	2025-04-21 14:18:00.917137+01	2025-04-21 14:18:00.91715+01	Need a projector	58	30	\N
82	2025-03-24 14:00:00+00	2025-03-24 18:00:00+00	COMPLETED	2025-04-21 12:50:23.839463+01	2025-04-21 12:50:23.847883+01		41	29	\N
136	2025-04-24 09:00:00+01	2025-04-24 10:00:00+01	PENDING	2025-04-22 23:37:00.625641+01	2025-04-22 23:37:00.625662+01	\N	62	22	\N
138	2025-04-24 11:00:00+01	2025-04-25 18:00:00+01	PENDING	2025-04-22 23:48:03.538844+01	2025-04-22 23:48:03.538858+01	\N	62	28	\N
83	2025-03-30 10:00:00+00	2025-03-30 12:00:00+00	COMPLETED	2025-04-21 12:50:23.857214+01	2025-04-21 12:50:23.865197+01	Past booking for Suburban Mall Event Space 10	54	30	\N
84	2025-04-09 19:00:00+01	2025-04-09 23:00:00+01	COMPLETED	2025-04-21 12:50:23.882032+01	2025-04-21 12:50:23.889941+01	Past booking for Tech Park Open Desk 2	52	22	\N
85	2025-04-01 12:00:00+00	2025-04-01 14:00:00+00	COMPLETED	2025-04-21 12:50:23.899217+01	2025-04-21 12:50:23.906163+01	Past booking for Suburban Mall Event Space 10	37	30	\N
86	2025-03-27 07:00:00+00	2025-03-27 09:00:00+00	CANCELLED	2025-04-21 12:50:23.917792+01	2025-04-21 12:50:23.925408+01	Past booking for Tech Park Private Office 18	40	38	\N
87	2025-03-25 12:00:00+00	2025-03-25 13:00:00+00	COMPLETED	2025-04-21 12:50:23.938412+01	2025-04-21 12:50:23.946892+01		47	25	\N
88	2025-04-18 21:00:00+01	2025-04-19 00:00:00+01	COMPLETED	2025-04-21 12:50:23.9563+01	2025-04-21 12:50:23.964695+01		56	40	\N
89	2025-03-26 14:00:00+00	2025-03-26 17:00:00+00	COMPLETED	2025-04-21 12:50:23.975592+01	2025-04-21 12:50:23.986291+01		45	27	\N
90	2025-04-01 16:00:00+00	2025-04-01 18:00:00+00	CANCELLED	2025-04-21 12:50:23.994739+01	2025-04-21 12:50:24.005561+01		41	24	\N
91	2025-04-16 15:00:00+01	2025-04-16 18:00:00+01	COMPLETED	2025-04-21 12:50:24.020102+01	2025-04-21 12:50:24.026795+01	Past booking for Tech Park Private Office 8	39	28	\N
92	2025-03-31 03:00:00+00	2025-03-31 07:00:00+00	CANCELLED	2025-04-21 12:50:24.038856+01	2025-04-21 12:50:24.047972+01		42	35	\N
93	2025-04-05 09:00:00+00	2025-04-05 11:00:00+00	COMPLETED	2025-04-21 12:50:24.05766+01	2025-04-21 12:50:24.067711+01	Past booking for University Area Quiet Zone 5	48	25	\N
94	2025-04-05 12:00:00+00	2025-04-05 20:00:00+00	COMPLETED	2025-04-21 12:50:24.076757+01	2025-04-21 12:50:24.086024+01		48	32	\N
95	2025-03-27 11:00:00+00	2025-03-27 15:00:00+00	COMPLETED	2025-04-21 12:50:24.098691+01	2025-04-21 12:50:24.108278+01	Past booking for East Side Meeting Room 6	53	26	\N
96	2025-04-10 07:00:00+01	2025-04-10 10:00:00+01	CANCELLED	2025-04-21 12:50:24.117909+01	2025-04-21 12:50:24.127734+01		54	23	\N
97	2025-03-24 04:00:00+00	2025-03-24 12:00:00+00	COMPLETED	2025-04-21 12:50:24.139075+01	2025-04-21 12:50:24.144968+01		49	36	\N
98	2025-03-24 05:00:00+00	2025-03-24 09:00:00+00	CANCELLED	2025-04-21 12:50:24.155815+01	2025-04-21 12:50:24.161611+01		44	33	\N
70	2025-03-25 16:00:00+00	2025-03-25 20:00:00+00	COMPLETED	2025-04-21 12:50:23.596934+01	2025-04-21 12:50:23.609121+01	Past booking for Tech Park Open Desk 2	43	22	\N
71	2025-04-19 20:00:00+01	2025-04-19 22:00:00+01	COMPLETED	2025-04-21 12:50:23.620198+01	2025-04-21 12:50:23.627882+01		49	32	\N
72	2025-03-26 21:00:00+00	2025-03-26 22:00:00+00	COMPLETED	2025-04-21 12:50:23.639308+01	2025-04-21 12:50:23.64535+01		53	36	\N
73	2025-04-07 11:00:00+01	2025-04-07 15:00:00+01	COMPLETED	2025-04-21 12:50:23.657964+01	2025-04-21 12:50:23.666962+01	Past booking for Tech Park Quiet Zone 4	44	24	\N
74	2025-04-15 04:00:00+01	2025-04-15 08:00:00+01	CANCELLED	2025-04-21 12:50:23.674157+01	2025-04-21 12:50:23.684266+01		43	31	\N
75	2025-04-20 09:00:00+01	2025-04-20 11:00:00+01	COMPLETED	2025-04-21 12:50:23.69364+01	2025-04-21 12:50:23.703059+01		55	32	\N
76	2025-04-18 18:00:00+01	2025-04-18 20:00:00+01	COMPLETED	2025-04-21 12:50:23.714834+01	2025-04-21 12:50:23.720805+01	Past booking for West End Quiet Zone 16	42	36	\N
77	2025-04-14 16:00:00+01	2025-04-14 18:00:00+01	COMPLETED	2025-04-21 12:50:23.73596+01	2025-04-21 12:50:23.745785+01	Past booking for University Area Quiet Zone 5	49	25	\N
78	2025-03-25 02:00:00+00	2025-03-25 04:00:00+00	COMPLETED	2025-04-21 12:50:23.757862+01	2025-04-21 12:50:23.766624+01		45	32	\N
79	2025-04-14 10:00:00+01	2025-04-14 12:00:00+01	COMPLETED	2025-04-21 12:50:23.777806+01	2025-04-21 12:50:23.783681+01	Past booking for Downtown Meeting Room 14	42	34	\N
80	2025-04-14 13:00:00+01	2025-04-14 16:00:00+01	COMPLETED	2025-04-21 12:50:23.799808+01	2025-04-21 12:50:23.809863+01		41	34	\N
81	2025-03-29 15:00:00+00	2025-03-29 17:00:00+00	CANCELLED	2025-04-21 12:50:23.819997+01	2025-04-21 12:50:23.827663+01		38	34	\N
99	2025-04-02 16:00:00+00	2025-04-02 20:00:00+00	CANCELLED	2025-04-21 12:50:24.177502+01	2025-04-21 12:50:24.18812+01	Past booking for Tech Park Private Office 8	43	28	\N
100	2025-04-14 15:00:00+01	2025-04-14 23:00:00+01	COMPLETED	2025-04-21 12:50:24.195823+01	2025-04-21 12:50:24.205155+01	Past booking for Tech Park Private Office 18	52	38	\N
137	2025-04-24 09:00:00+01	2025-04-24 10:00:00+01	PENDING	2025-04-22 23:38:15.437349+01	2025-04-22 23:38:15.437361+01	\N	62	28	\N
112	2025-05-15 10:00:00+01	2025-05-15 18:00:00+01	CONFIRMED	2025-04-21 12:50:24.439387+01	2025-04-21 12:50:24.449526+01		42	21	\N
113	2025-05-03 14:00:00+01	2025-05-03 22:00:00+01	PENDING	2025-04-21 12:50:24.460304+01	2025-04-21 12:50:24.460317+01	Future booking for Tech Park Open Desk 15	42	35	\N
114	2025-05-05 15:00:00+01	2025-05-05 18:00:00+01	CONFIRMED	2025-04-21 12:50:24.47445+01	2025-04-21 12:50:24.481437+01		56	34	\N
115	2025-04-29 16:00:00+01	2025-04-29 20:00:00+01	CONFIRMED	2025-04-21 12:50:24.494933+01	2025-04-21 12:50:24.503788+01	Future booking for Tech Park Private Office 18	48	38	\N
116	2025-04-29 20:00:00+01	2025-04-29 21:00:00+01	CONFIRMED	2025-04-21 12:50:24.518355+01	2025-04-21 12:50:24.525667+01		49	40	\N
117	2025-05-17 13:00:00+01	2025-05-17 16:00:00+01	CONFIRMED	2025-04-21 12:50:24.537343+01	2025-04-21 12:50:24.543717+01		50	39	\N
118	2025-04-25 11:00:00+01	2025-04-25 15:00:00+01	CONFIRMED	2025-04-21 12:50:24.555438+01	2025-04-21 12:50:24.563188+01	Future booking for East Side Meeting Room 6	56	26	\N
119	2025-05-08 14:00:00+01	2025-05-08 18:00:00+01	PENDING	2025-04-21 12:50:24.57382+01	2025-04-21 12:50:24.573826+01		56	24	\N
120	2025-05-15 13:00:00+01	2025-05-15 14:00:00+01	PENDING	2025-04-21 12:50:24.590134+01	2025-04-21 12:50:24.590141+01		43	26	\N
121	2025-04-23 12:00:00+01	2025-04-23 14:00:00+01	PENDING	2025-04-21 12:50:24.607052+01	2025-04-21 12:50:24.607058+01	Future booking for Tech Park Private Office 18	38	38	\N
122	2025-04-21 08:00:00+01	2025-04-21 09:00:00+01	CONFIRMED	2025-04-21 12:50:24.618409+01	2025-04-21 12:50:24.625049+01	Future booking for East Side Quiet Zone 12	45	32	\N
123	2025-04-27 02:00:00+01	2025-04-27 10:00:00+01	PENDING	2025-04-21 12:50:24.636072+01	2025-04-21 12:50:24.636079+01		51	32	\N
124	2025-04-22 20:00:00+01	2025-04-22 23:00:00+01	CONFIRMED	2025-04-21 12:50:24.64999+01	2025-04-21 12:50:24.658757+01		45	31	\N
125	2025-04-25 08:00:00+01	2025-04-25 10:00:00+01	CONFIRMED	2025-04-21 12:50:24.669005+01	2025-04-21 12:50:24.67716+01		47	29	\N
126	2025-05-10 06:00:00+01	2025-05-10 10:00:00+01	CONFIRMED	2025-04-21 12:50:24.691289+01	2025-04-21 12:50:24.699083+01		54	23	\N
101	2025-03-23 01:00:00+00	2025-03-23 03:00:00+00	COMPLETED	2025-04-21 12:50:24.214787+01	2025-04-21 12:50:24.221996+01	Past booking for Tech Park Private Office 8	39	28	\N
102	2025-04-11 08:00:00+01	2025-04-11 12:00:00+01	CANCELLED	2025-04-21 12:50:24.235952+01	2025-04-21 12:50:24.241629+01		39	29	\N
103	2025-04-10 12:00:00+01	2025-04-10 14:00:00+01	COMPLETED	2025-04-21 12:50:24.251182+01	2025-04-21 12:50:24.259456+01		48	37	\N
104	2025-04-05 10:00:00+00	2025-04-05 13:00:00+00	COMPLETED	2025-04-21 12:50:24.269088+01	2025-04-21 12:50:24.278388+01		48	33	\N
105	2025-04-06 12:00:00+01	2025-04-06 13:00:00+01	CANCELLED	2025-04-21 12:50:24.288558+01	2025-04-21 12:50:24.299948+01	Past booking for Tech Park Open Desk 15	37	35	\N
106	2025-04-19 07:00:00+01	2025-04-19 10:00:00+01	COMPLETED	2025-04-21 12:50:24.310533+01	2025-04-21 12:50:24.319766+01		37	23	\N
107	2025-04-16 15:00:00+01	2025-04-16 18:00:00+01	COMPLETED	2025-04-21 12:50:24.330901+01	2025-04-21 12:50:24.338909+01		41	40	\N
108	2025-04-19 15:00:00+01	2025-04-19 19:00:00+01	COMPLETED	2025-04-21 12:50:24.34708+01	2025-04-21 12:50:24.355481+01		53	24	\N
109	2025-04-17 21:00:00+01	2025-04-17 23:00:00+01	CANCELLED	2025-04-21 12:50:24.370914+01	2025-04-21 12:50:24.378889+01		39	22	\N
110	2025-04-15 08:00:00+01	2025-04-15 10:00:00+01	COMPLETED	2025-04-21 12:50:24.388988+01	2025-04-21 12:50:24.396015+01		53	27	\N
111	2025-04-18 10:00:00+01	2025-04-18 11:00:00+01	CANCELLED	2025-04-21 12:50:24.406486+01	2025-04-21 12:50:24.421873+01	Past booking for Downtown Meeting Room 14	51	34	\N
127	2025-05-08 21:00:00+01	2025-05-08 23:00:00+01	CONFIRMED	2025-04-21 12:50:24.709743+01	2025-04-21 12:50:24.718388+01	Future booking for East Side Quiet Zone 12	52	32	\N
128	2025-05-06 05:00:00+01	2025-05-06 06:00:00+01	PENDING	2025-04-21 12:50:24.728403+01	2025-04-21 12:50:24.728415+01	Future booking for Tech Park Private Office 8	55	28	\N
129	2025-04-29 10:00:00+01	2025-04-29 18:00:00+01	CONFIRMED	2025-04-21 12:50:24.739329+01	2025-04-21 12:50:24.745994+01		56	30	\N
130	2025-04-28 15:00:00+01	2025-04-28 19:00:00+01	CONFIRMED	2025-04-21 12:50:24.756771+01	2025-04-21 12:50:24.767234+01	Future booking for East Side Meeting Room 6	42	26	\N
131	2025-04-23 14:00:00+01	2025-04-23 16:00:00+01	CONFIRMED	2025-04-21 12:50:24.775668+01	2025-04-21 12:50:24.785492+01		46	30	\N
132	2025-04-29 11:00:00+01	2025-04-29 14:00:00+01	CONFIRMED	2025-04-21 12:50:24.794204+01	2025-04-21 12:50:24.802175+01		46	24	\N
133	2025-05-15 14:00:00+01	2025-05-15 18:00:00+01	CONFIRMED	2025-04-21 12:50:24.814497+01	2025-04-21 12:50:24.821713+01	Future booking for Suburban Mall Event Space 10	55	30	\N
134	2025-05-02 09:00:00+01	2025-05-02 10:00:00+01	PENDING	2025-04-21 12:50:24.832967+01	2025-04-21 12:50:24.832974+01	Future booking for Suburban Mall Quiet Zone 13	41	33	\N
\.


--
-- Data for Name: bookings_teaminvitation; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.bookings_teaminvitation (id, created_at, accepted, invitee_id, leader_id) FROM stdin;
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	contenttypes	contenttype
5	sessions	session
6	users	user
7	workspaces	amenity
8	workspaces	workspace
9	workspaces	workspacetype
10	bookings	booking
11	authtoken	token
12	authtoken	tokenproxy
13	notifications	notification
14	bookings	teaminvitation
15	teams	team
16	teams	teaminvitation
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2025-04-16 20:27:09.735945+01
2	contenttypes	0002_remove_content_type_name	2025-04-16 20:27:09.75268+01
3	auth	0001_initial	2025-04-16 20:27:09.893178+01
4	auth	0002_alter_permission_name_max_length	2025-04-16 20:27:09.903822+01
5	auth	0003_alter_user_email_max_length	2025-04-16 20:27:09.923584+01
6	auth	0004_alter_user_username_opts	2025-04-16 20:27:09.936615+01
7	auth	0005_alter_user_last_login_null	2025-04-16 20:27:09.955759+01
8	auth	0006_require_contenttypes_0002	2025-04-16 20:27:09.9665+01
9	auth	0007_alter_validators_add_error_messages	2025-04-16 20:27:09.977308+01
10	auth	0008_alter_user_username_max_length	2025-04-16 20:27:10.023455+01
11	auth	0009_alter_user_last_name_max_length	2025-04-16 20:27:10.035022+01
12	auth	0010_alter_group_name_max_length	2025-04-16 20:27:10.050918+01
13	auth	0011_update_proxy_permissions	2025-04-16 20:27:10.067291+01
14	auth	0012_alter_user_first_name_max_length	2025-04-16 20:27:10.078914+01
15	users	0001_initial	2025-04-16 20:27:10.22848+01
16	admin	0001_initial	2025-04-16 20:27:10.286514+01
17	admin	0002_logentry_remove_auto_add	2025-04-16 20:27:10.305462+01
18	admin	0003_logentry_add_action_flag_choices	2025-04-16 20:27:10.333137+01
19	sessions	0001_initial	2025-04-16 20:27:10.382232+01
20	workspaces	0001_initial	2025-04-16 21:42:38.922327+01
21	bookings	0001_initial	2025-04-17 17:56:01.951802+01
22	authtoken	0001_initial	2025-04-19 14:53:40.780048+01
23	authtoken	0002_auto_20160226_1747	2025-04-19 14:53:40.840674+01
24	authtoken	0003_tokenproxy	2025-04-19 14:53:40.846357+01
25	authtoken	0004_alter_tokenproxy_options	2025-04-19 14:53:40.860833+01
26	users	0002_alter_user_user_type	2025-04-19 15:44:15.176934+01
27	users	0002_user_date_joined	2025-04-19 16:43:10.666797+01
28	notifications	0001_initial	2025-04-19 21:10:08.974362+01
29	bookings	0002_booking_booked_by_teaminvitation	2025-04-21 12:19:19.780492+01
30	users	0003_user_team_leader_alter_user_user_type	2025-04-21 12:19:19.840987+01
31	teams	0001_initial	2025-04-21 12:45:09.901212+01
32	teams	0002_teaminvitation	2025-04-21 19:57:33.092605+01
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
\.


--
-- Data for Name: notifications_notification; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.notifications_notification (id, notification_type, message, is_read, created_at, read_at, booking_id, user_id) FROM stdin;
282	BOOKING_CREATED	You've booked Suburban Mall Event Space 10 from 2025-04-22 10:00 to 2025-04-22 12:00	t	2025-04-21 14:18:00.926513+01	2025-04-21 16:47:46.826203+01	135	58
283	BOOKING_CREATED	You've booked Tech Park Open Desk 2 from 2025-04-24 08:00 to 2025-04-24 09:00	f	2025-04-22 23:37:00.659363+01	\N	136	62
145	BOOKING_COMPLETED	Your booking for Tech Park Open Desk 2 has been completed	f	2025-04-21 12:50:23.61024+01	\N	70	43
147	BOOKING_COMPLETED	Your booking for East Side Quiet Zone 12 has been completed	f	2025-04-21 12:50:23.628895+01	\N	71	49
148	BOOKING_CREATED	You've booked West End Quiet Zone 16 from 2025-03-26 21:00 to 2025-03-26 22:00	f	2025-04-21 12:50:23.640401+01	\N	72	53
149	BOOKING_COMPLETED	Your booking for West End Quiet Zone 16 has been completed	f	2025-04-21 12:50:23.646662+01	\N	72	53
150	BOOKING_CREATED	You've booked Tech Park Quiet Zone 4 from 2025-04-07 10:00 to 2025-04-07 14:00	f	2025-04-21 12:50:23.65878+01	\N	73	44
151	BOOKING_COMPLETED	Your booking for Tech Park Quiet Zone 4 has been completed	f	2025-04-21 12:50:23.668445+01	\N	73	44
152	BOOKING_CREATED	You've booked Suburban Mall Event Space 11 from 2025-04-15 03:00 to 2025-04-15 07:00	f	2025-04-21 12:50:23.674957+01	\N	74	43
153	BOOKING_CANCELLED	Your booking for Suburban Mall Event Space 11 has been cancelled	f	2025-04-21 12:50:23.685511+01	\N	74	43
154	BOOKING_CREATED	You've booked East Side Quiet Zone 12 from 2025-04-20 08:00 to 2025-04-20 10:00	f	2025-04-21 12:50:23.696983+01	\N	75	55
155	BOOKING_COMPLETED	Your booking for East Side Quiet Zone 12 has been completed	f	2025-04-21 12:50:23.704178+01	\N	75	55
156	BOOKING_CREATED	You've booked West End Quiet Zone 16 from 2025-04-18 17:00 to 2025-04-18 19:00	f	2025-04-21 12:50:23.715761+01	\N	76	42
159	BOOKING_COMPLETED	Your booking for University Area Quiet Zone 5 has been completed	f	2025-04-21 12:50:23.747026+01	\N	77	49
160	BOOKING_CREATED	You've booked East Side Quiet Zone 12 from 2025-03-25 02:00 to 2025-03-25 04:00	f	2025-04-21 12:50:23.759333+01	\N	78	45
165	BOOKING_COMPLETED	Your booking for Downtown Meeting Room 14 has been completed	f	2025-04-21 12:50:23.810937+01	\N	80	41
164	BOOKING_CREATED	You've booked Downtown Meeting Room 14 from 2025-04-14 12:00 to 2025-04-14 15:00	t	2025-04-21 12:50:23.800929+01	2025-04-21 12:50:24.868867+01	80	41
157	BOOKING_COMPLETED	Your booking for West End Quiet Zone 16 has been completed	t	2025-04-21 12:50:23.722484+01	2025-04-21 12:50:24.874751+01	76	42
158	BOOKING_CREATED	You've booked University Area Quiet Zone 5 from 2025-04-14 15:00 to 2025-04-14 17:00	t	2025-04-21 12:50:23.736755+01	2025-04-21 12:50:24.90293+01	77	49
146	BOOKING_CREATED	You've booked East Side Quiet Zone 12 from 2025-04-19 19:00 to 2025-04-19 21:00	t	2025-04-21 12:50:23.621694+01	2025-04-21 12:50:24.919677+01	71	49
144	BOOKING_CREATED	You've booked Tech Park Open Desk 2 from 2025-03-25 16:00 to 2025-03-25 20:00	t	2025-04-21 12:50:23.599332+01	2025-04-21 12:50:24.922511+01	70	43
161	BOOKING_COMPLETED	Your booking for East Side Quiet Zone 12 has been completed	t	2025-04-21 12:50:23.767957+01	2025-04-21 12:50:25.02486+01	78	45
162	BOOKING_CREATED	You've booked Downtown Meeting Room 14 from 2025-04-14 09:00 to 2025-04-14 11:00	t	2025-04-21 12:50:23.778696+01	2025-04-21 12:50:25.067505+01	79	42
163	BOOKING_COMPLETED	Your booking for Downtown Meeting Room 14 has been completed	t	2025-04-21 12:50:23.785143+01	2025-04-21 12:50:25.07257+01	79	42
284	BOOKING_CREATED	You've booked Tech Park Private Office 8 from 2025-04-24 08:00 to 2025-04-24 09:00	f	2025-04-22 23:38:15.443182+01	\N	137	62
166	BOOKING_CREATED	You've booked Downtown Meeting Room 14 from 2025-03-29 15:00 to 2025-03-29 17:00	f	2025-04-21 12:50:23.821543+01	\N	81	38
168	BOOKING_CREATED	You've booked University Area Meeting Room 9 from 2025-03-24 14:00 to 2025-03-24 18:00	f	2025-04-21 12:50:23.840685+01	\N	82	41
169	BOOKING_COMPLETED	Your booking for University Area Meeting Room 9 has been completed	f	2025-04-21 12:50:23.849292+01	\N	82	41
170	BOOKING_CREATED	You've booked Suburban Mall Event Space 10 from 2025-03-30 10:00 to 2025-03-30 12:00	f	2025-04-21 12:50:23.85802+01	\N	83	54
175	BOOKING_COMPLETED	Your booking for Suburban Mall Event Space 10 has been completed	f	2025-04-21 12:50:23.90716+01	\N	85	37
178	BOOKING_CREATED	You've booked University Area Quiet Zone 5 from 2025-03-25 12:00 to 2025-03-25 13:00	f	2025-04-21 12:50:23.940257+01	\N	87	47
179	BOOKING_COMPLETED	Your booking for University Area Quiet Zone 5 has been completed	f	2025-04-21 12:50:23.948135+01	\N	87	47
180	BOOKING_CREATED	You've booked Downtown Open Desk 20 from 2025-04-18 20:00 to 2025-04-18 23:00	f	2025-04-21 12:50:23.9574+01	\N	88	56
181	BOOKING_COMPLETED	Your booking for Downtown Open Desk 20 has been completed	f	2025-04-21 12:50:23.966841+01	\N	88	56
172	BOOKING_CREATED	You've booked Tech Park Open Desk 2 from 2025-04-09 18:00 to 2025-04-09 22:00	t	2025-04-21 12:50:23.883403+01	2025-04-21 12:50:24.883923+01	84	52
171	BOOKING_COMPLETED	Your booking for Suburban Mall Event Space 10 has been completed	t	2025-04-21 12:50:23.866216+01	2025-04-21 12:50:24.906062+01	83	54
167	BOOKING_CANCELLED	Your booking for Downtown Meeting Room 14 has been cancelled	t	2025-04-21 12:50:23.828671+01	2025-04-21 12:50:24.937404+01	81	38
173	BOOKING_COMPLETED	Your booking for Tech Park Open Desk 2 has been completed	t	2025-04-21 12:50:23.890981+01	2025-04-21 12:50:24.96849+01	84	52
176	BOOKING_CREATED	You've booked Tech Park Private Office 18 from 2025-03-27 07:00 to 2025-03-27 09:00	t	2025-04-21 12:50:23.918666+01	2025-04-21 12:50:24.993277+01	86	40
177	BOOKING_CANCELLED	Your booking for Tech Park Private Office 18 has been cancelled	t	2025-04-21 12:50:23.926513+01	2025-04-21 12:50:25.006153+01	86	40
185	BOOKING_CANCELLED	Your booking for Tech Park Quiet Zone 4 has been cancelled	t	2025-04-21 12:50:24.006596+01	2025-04-21 12:50:25.010212+01	90	41
182	BOOKING_CREATED	You've booked University Area Meeting Room 7 from 2025-03-26 14:00 to 2025-03-26 17:00	t	2025-04-21 12:50:23.976423+01	2025-04-21 12:50:25.013928+01	89	45
184	BOOKING_CREATED	You've booked Tech Park Quiet Zone 4 from 2025-04-01 16:00 to 2025-04-01 18:00	t	2025-04-21 12:50:23.996141+01	2025-04-21 12:50:25.032006+01	90	41
183	BOOKING_COMPLETED	Your booking for University Area Meeting Room 7 has been completed	t	2025-04-21 12:50:23.98811+01	2025-04-21 12:50:25.047253+01	89	45
174	BOOKING_CREATED	You've booked Suburban Mall Event Space 10 from 2025-04-01 12:00 to 2025-04-01 14:00	t	2025-04-21 12:50:23.900543+01	2025-04-21 12:50:25.04995+01	85	37
285	BOOKING_CREATED	You've booked Tech Park Private Office 8 from 2025-04-24 10:00 to 2025-04-25 17:00	f	2025-04-22 23:48:03.543882+01	\N	138	62
186	BOOKING_CREATED	You've booked Tech Park Private Office 8 from 2025-04-16 14:00 to 2025-04-16 17:00	f	2025-04-21 12:50:24.021113+01	\N	91	39
188	BOOKING_CREATED	You've booked Tech Park Open Desk 15 from 2025-03-31 03:00 to 2025-03-31 07:00	f	2025-04-21 12:50:24.039683+01	\N	92	42
189	BOOKING_CANCELLED	Your booking for Tech Park Open Desk 15 has been cancelled	f	2025-04-21 12:50:24.049246+01	\N	92	42
190	BOOKING_CREATED	You've booked University Area Quiet Zone 5 from 2025-04-05 09:00 to 2025-04-05 11:00	f	2025-04-21 12:50:24.058661+01	\N	93	48
192	BOOKING_CREATED	You've booked East Side Quiet Zone 12 from 2025-04-05 12:00 to 2025-04-05 20:00	f	2025-04-21 12:50:24.078393+01	\N	94	48
193	BOOKING_COMPLETED	Your booking for East Side Quiet Zone 12 has been completed	f	2025-04-21 12:50:24.087436+01	\N	94	48
194	BOOKING_CREATED	You've booked East Side Meeting Room 6 from 2025-03-27 11:00 to 2025-03-27 15:00	f	2025-04-21 12:50:24.100023+01	\N	95	53
195	BOOKING_COMPLETED	Your booking for East Side Meeting Room 6 has been completed	f	2025-04-21 12:50:24.10977+01	\N	95	53
198	BOOKING_CREATED	You've booked West End Quiet Zone 16 from 2025-03-24 04:00 to 2025-03-24 12:00	f	2025-04-21 12:50:24.139905+01	\N	97	49
200	BOOKING_CREATED	You've booked Suburban Mall Quiet Zone 13 from 2025-03-24 05:00 to 2025-03-24 09:00	f	2025-04-21 12:50:24.156652+01	\N	98	44
202	BOOKING_CREATED	You've booked Tech Park Private Office 8 from 2025-04-02 16:00 to 2025-04-02 20:00	f	2025-04-21 12:50:24.178312+01	\N	99	43
196	BOOKING_CREATED	You've booked University Area Quiet Zone 3 from 2025-04-10 06:00 to 2025-04-10 09:00	t	2025-04-21 12:50:24.118966+01	2025-04-21 12:50:24.89365+01	96	54
191	BOOKING_COMPLETED	Your booking for University Area Quiet Zone 5 has been completed	t	2025-04-21 12:50:24.068927+01	2025-04-21 12:50:24.896746+01	93	48
201	BOOKING_CANCELLED	Your booking for Suburban Mall Quiet Zone 13 has been cancelled	t	2025-04-21 12:50:24.163261+01	2025-04-21 12:50:24.915383+01	98	44
197	BOOKING_CANCELLED	Your booking for University Area Quiet Zone 3 has been cancelled	t	2025-04-21 12:50:24.129063+01	2025-04-21 12:50:24.987464+01	96	54
199	BOOKING_COMPLETED	Your booking for West End Quiet Zone 16 has been completed	t	2025-04-21 12:50:24.14609+01	2025-04-21 12:50:25.034768+01	97	49
187	BOOKING_COMPLETED	Your booking for Tech Park Private Office 8 has been completed	t	2025-04-21 12:50:24.028663+01	2025-04-21 12:50:25.056648+01	91	39
203	BOOKING_CANCELLED	Your booking for Tech Park Private Office 8 has been cancelled	f	2025-04-21 12:50:24.189134+01	\N	99	43
204	BOOKING_CREATED	You've booked Tech Park Private Office 18 from 2025-04-14 14:00 to 2025-04-14 22:00	f	2025-04-21 12:50:24.196656+01	\N	100	52
205	BOOKING_COMPLETED	Your booking for Tech Park Private Office 18 has been completed	f	2025-04-21 12:50:24.206209+01	\N	100	52
206	BOOKING_CREATED	You've booked Tech Park Private Office 8 from 2025-03-23 01:00 to 2025-03-23 03:00	f	2025-04-21 12:50:24.215869+01	\N	101	39
207	BOOKING_COMPLETED	Your booking for Tech Park Private Office 8 has been completed	f	2025-04-21 12:50:24.223125+01	\N	101	39
208	BOOKING_CREATED	You've booked University Area Meeting Room 9 from 2025-04-11 07:00 to 2025-04-11 11:00	f	2025-04-21 12:50:24.236857+01	\N	102	39
210	BOOKING_CREATED	You've booked Suburban Mall Private Office 17 from 2025-04-10 11:00 to 2025-04-10 13:00	f	2025-04-21 12:50:24.252186+01	\N	103	48
211	BOOKING_COMPLETED	Your booking for Suburban Mall Private Office 17 has been completed	f	2025-04-21 12:50:24.262462+01	\N	103	48
213	BOOKING_COMPLETED	Your booking for Suburban Mall Quiet Zone 13 has been completed	f	2025-04-21 12:50:24.279826+01	\N	104	48
214	BOOKING_CREATED	You've booked Tech Park Open Desk 15 from 2025-04-06 11:00 to 2025-04-06 12:00	f	2025-04-21 12:50:24.292153+01	\N	105	37
218	BOOKING_CREATED	You've booked Downtown Open Desk 20 from 2025-04-16 14:00 to 2025-04-16 17:00	f	2025-04-21 12:50:24.332183+01	\N	107	41
219	BOOKING_COMPLETED	Your booking for Downtown Open Desk 20 has been completed	f	2025-04-21 12:50:24.339997+01	\N	107	41
220	BOOKING_CREATED	You've booked Tech Park Quiet Zone 4 from 2025-04-19 14:00 to 2025-04-19 18:00	f	2025-04-21 12:50:24.348169+01	\N	108	53
223	BOOKING_CANCELLED	Your booking for Tech Park Open Desk 2 has been cancelled	f	2025-04-21 12:50:24.380197+01	\N	109	39
224	BOOKING_CREATED	You've booked University Area Meeting Room 7 from 2025-04-15 07:00 to 2025-04-15 09:00	f	2025-04-21 12:50:24.39025+01	\N	110	53
226	BOOKING_CREATED	You've booked Downtown Meeting Room 14 from 2025-04-18 09:00 to 2025-04-18 10:00	f	2025-04-21 12:50:24.407812+01	\N	111	51
227	BOOKING_CANCELLED	Your booking for Downtown Meeting Room 14 has been cancelled	f	2025-04-21 12:50:24.423678+01	\N	111	51
228	BOOKING_CREATED	You've booked Downtown Event Space 1 from 2025-05-15 09:00 to 2025-05-15 17:00	f	2025-04-21 12:50:24.44059+01	\N	112	42
229	BOOKING_CONFIRMED	Your booking for Downtown Event Space 1 has been confirmed	f	2025-04-21 12:50:24.450984+01	\N	112	42
230	BOOKING_CREATED	You've booked Tech Park Open Desk 15 from 2025-05-03 13:00 to 2025-05-03 21:00	f	2025-04-21 12:50:24.461358+01	\N	113	42
233	BOOKING_CREATED	You've booked Tech Park Private Office 18 from 2025-04-29 15:00 to 2025-04-29 19:00	f	2025-04-21 12:50:24.496408+01	\N	115	48
236	BOOKING_CONFIRMED	Your booking for Downtown Open Desk 20 has been confirmed	f	2025-04-21 12:50:24.526709+01	\N	116	49
237	BOOKING_CREATED	You've booked West End Quiet Zone 19 from 2025-05-17 12:00 to 2025-05-17 15:00	f	2025-04-21 12:50:24.538647+01	\N	117	50
239	BOOKING_CREATED	You've booked East Side Meeting Room 6 from 2025-04-25 10:00 to 2025-04-25 14:00	f	2025-04-21 12:50:24.556439+01	\N	118	56
244	BOOKING_CREATED	You've booked East Side Quiet Zone 12 from 2025-04-21 07:00 to 2025-04-21 08:00	f	2025-04-21 12:50:24.619431+01	\N	122	45
247	BOOKING_CREATED	You've booked Suburban Mall Event Space 11 from 2025-04-22 19:00 to 2025-04-22 22:00	f	2025-04-21 12:50:24.65103+01	\N	124	45
249	BOOKING_CREATED	You've booked University Area Meeting Room 9 from 2025-04-25 07:00 to 2025-04-25 09:00	f	2025-04-21 12:50:24.669865+01	\N	125	47
250	BOOKING_CONFIRMED	Your booking for University Area Meeting Room 9 has been confirmed	f	2025-04-21 12:50:24.678253+01	\N	125	47
251	BOOKING_CREATED	You've booked University Area Quiet Zone 3 from 2025-05-10 05:00 to 2025-05-10 09:00	f	2025-04-21 12:50:24.692288+01	\N	126	54
254	BOOKING_CONFIRMED	Your booking for East Side Quiet Zone 12 has been confirmed	f	2025-04-21 12:50:24.720678+01	\N	127	52
255	BOOKING_CREATED	You've booked Tech Park Private Office 8 from 2025-05-06 04:00 to 2025-05-06 05:00	f	2025-04-21 12:50:24.729416+01	\N	128	55
257	BOOKING_CONFIRMED	Your booking for Suburban Mall Event Space 10 has been confirmed	f	2025-04-21 12:50:24.750525+01	\N	129	56
260	BOOKING_CREATED	You've booked Suburban Mall Event Space 10 from 2025-04-23 13:00 to 2025-04-23 15:00	f	2025-04-21 12:50:24.77652+01	\N	131	46
261	BOOKING_CONFIRMED	Your booking for Suburban Mall Event Space 10 has been confirmed	f	2025-04-21 12:50:24.786595+01	\N	131	46
262	BOOKING_CREATED	You've booked Tech Park Quiet Zone 4 from 2025-04-29 10:00 to 2025-04-29 13:00	f	2025-04-21 12:50:24.79676+01	\N	132	46
263	BOOKING_CONFIRMED	Your booking for Tech Park Quiet Zone 4 has been confirmed	f	2025-04-21 12:50:24.803281+01	\N	132	46
266	BOOKING_CREATED	You've booked Suburban Mall Quiet Zone 13 from 2025-05-02 08:00 to 2025-05-02 09:00	f	2025-04-21 12:50:24.833855+01	\N	134	41
267	BOOKING_REMINDER	Reminder: You have a booking for Downtown Event Space 1 starting at 2025-05-15 09:00	f	2025-04-21 12:50:24.835111+01	\N	112	42
268	BOOKING_REMINDER	Reminder: You have a booking for Downtown Meeting Room 14 starting at 2025-05-05 14:00	f	2025-04-21 12:50:24.837401+01	\N	114	56
269	BOOKING_REMINDER	Reminder: You have a booking for Tech Park Private Office 18 starting at 2025-04-29 15:00	f	2025-04-21 12:50:24.838848+01	\N	115	48
270	BOOKING_REMINDER	Reminder: You have a booking for Downtown Open Desk 20 starting at 2025-04-29 19:00	f	2025-04-21 12:50:24.841498+01	\N	116	49
271	BOOKING_REMINDER	Reminder: You have a booking for West End Quiet Zone 19 starting at 2025-05-17 12:00	f	2025-04-21 12:50:24.843821+01	\N	117	50
272	BOOKING_REMINDER	Reminder: You have a booking for East Side Meeting Room 6 starting at 2025-04-25 10:00	f	2025-04-21 12:50:24.845328+01	\N	118	56
273	BOOKING_REMINDER	Reminder: You have a booking for Suburban Mall Event Space 11 starting at 2025-04-22 19:00	f	2025-04-21 12:50:24.846655+01	\N	124	45
274	BOOKING_REMINDER	Reminder: You have a booking for University Area Meeting Room 9 starting at 2025-04-25 07:00	f	2025-04-21 12:50:24.848647+01	\N	125	47
276	BOOKING_REMINDER	Reminder: You have a booking for East Side Quiet Zone 12 starting at 2025-05-08 20:00	f	2025-04-21 12:50:24.851645+01	\N	127	52
277	BOOKING_REMINDER	Reminder: You have a booking for Suburban Mall Event Space 10 starting at 2025-04-29 09:00	f	2025-04-21 12:50:24.85337+01	\N	129	56
278	BOOKING_REMINDER	Reminder: You have a booking for East Side Meeting Room 6 starting at 2025-04-28 14:00	f	2025-04-21 12:50:24.857853+01	\N	130	42
280	BOOKING_REMINDER	Reminder: You have a booking for Tech Park Quiet Zone 4 starting at 2025-04-29 10:00	f	2025-04-21 12:50:24.861907+01	\N	132	46
253	BOOKING_CREATED	You've booked East Side Quiet Zone 12 from 2025-05-08 20:00 to 2025-05-08 22:00	t	2025-04-21 12:50:24.710734+01	2025-04-21 12:50:24.878058+01	127	52
221	BOOKING_COMPLETED	Your booking for Tech Park Quiet Zone 4 has been completed	t	2025-04-21 12:50:24.356818+01	2025-04-21 12:50:24.881018+01	108	53
235	BOOKING_CREATED	You've booked Downtown Open Desk 20 from 2025-04-29 19:00 to 2025-04-29 20:00	t	2025-04-21 12:50:24.520303+01	2025-04-21 12:50:24.889651+01	116	49
265	BOOKING_CONFIRMED	Your booking for Suburban Mall Event Space 10 has been confirmed	t	2025-04-21 12:50:24.82308+01	2025-04-21 12:50:24.899246+01	133	55
238	BOOKING_CONFIRMED	Your booking for West End Quiet Zone 19 has been confirmed	t	2025-04-21 12:50:24.545503+01	2025-04-21 12:50:24.909424+01	117	50
256	BOOKING_CREATED	You've booked Suburban Mall Event Space 10 from 2025-04-29 09:00 to 2025-04-29 17:00	t	2025-04-21 12:50:24.740173+01	2025-04-21 12:50:24.925373+01	129	56
217	BOOKING_COMPLETED	Your booking for University Area Quiet Zone 3 has been completed	t	2025-04-21 12:50:24.323022+01	2025-04-21 12:50:24.932374+01	106	37
234	BOOKING_CONFIRMED	Your booking for Tech Park Private Office 18 has been confirmed	t	2025-04-21 12:50:24.506538+01	2025-04-21 12:50:24.934893+01	115	48
231	BOOKING_CREATED	You've booked Downtown Meeting Room 14 from 2025-05-05 14:00 to 2025-05-05 17:00	t	2025-04-21 12:50:24.475501+01	2025-04-21 12:50:24.940315+01	114	56
275	BOOKING_REMINDER	Reminder: You have a booking for University Area Quiet Zone 3 starting at 2025-05-10 05:00	t	2025-04-21 12:50:24.85018+01	2025-04-21 12:50:24.945047+01	126	54
241	BOOKING_CREATED	You've booked Tech Park Quiet Zone 4 from 2025-05-08 13:00 to 2025-05-08 17:00	t	2025-04-21 12:50:24.575064+01	2025-04-21 12:50:24.950478+01	119	56
243	BOOKING_CREATED	You've booked Tech Park Private Office 18 from 2025-04-23 11:00 to 2025-04-23 13:00	t	2025-04-21 12:50:24.607851+01	2025-04-21 12:50:24.952866+01	121	38
264	BOOKING_CREATED	You've booked Suburban Mall Event Space 10 from 2025-05-15 13:00 to 2025-05-15 17:00	t	2025-04-21 12:50:24.815564+01	2025-04-21 12:50:24.955792+01	133	55
215	BOOKING_CANCELLED	Your booking for Tech Park Open Desk 15 has been cancelled	t	2025-04-21 12:50:24.301678+01	2025-04-21 12:50:24.958913+01	105	37
222	BOOKING_CREATED	You've booked Tech Park Open Desk 2 from 2025-04-17 20:00 to 2025-04-17 22:00	t	2025-04-21 12:50:24.371752+01	2025-04-21 12:50:24.965189+01	109	39
252	BOOKING_CONFIRMED	Your booking for University Area Quiet Zone 3 has been confirmed	t	2025-04-21 12:50:24.7008+01	2025-04-21 12:50:24.971353+01	126	54
240	BOOKING_CONFIRMED	Your booking for East Side Meeting Room 6 has been confirmed	t	2025-04-21 12:50:24.566734+01	2025-04-21 12:50:24.973886+01	118	56
281	BOOKING_REMINDER	Reminder: You have a booking for Suburban Mall Event Space 10 starting at 2025-05-15 13:00	t	2025-04-21 12:50:24.863285+01	2025-04-21 12:50:24.979219+01	133	55
216	BOOKING_CREATED	You've booked University Area Quiet Zone 3 from 2025-04-19 06:00 to 2025-04-19 09:00	t	2025-04-21 12:50:24.313725+01	2025-04-21 12:50:24.983588+01	106	37
246	BOOKING_CREATED	You've booked East Side Quiet Zone 12 from 2025-04-27 01:00 to 2025-04-27 09:00	t	2025-04-21 12:50:24.636909+01	2025-04-21 12:50:24.989927+01	123	51
248	BOOKING_CONFIRMED	Your booking for Suburban Mall Event Space 11 has been confirmed	t	2025-04-21 12:50:24.659961+01	2025-04-21 12:50:24.997208+01	124	45
245	BOOKING_CONFIRMED	Your booking for East Side Quiet Zone 12 has been confirmed	t	2025-04-21 12:50:24.627276+01	2025-04-21 12:50:25.002782+01	122	45
232	BOOKING_CONFIRMED	Your booking for Downtown Meeting Room 14 has been confirmed	t	2025-04-21 12:50:24.483358+01	2025-04-21 12:50:25.016687+01	114	56
209	BOOKING_CANCELLED	Your booking for University Area Meeting Room 9 has been cancelled	t	2025-04-21 12:50:24.242838+01	2025-04-21 12:50:25.020168+01	102	39
212	BOOKING_CREATED	You've booked Suburban Mall Quiet Zone 13 from 2025-04-05 10:00 to 2025-04-05 13:00	t	2025-04-21 12:50:24.270269+01	2025-04-21 12:50:25.028473+01	104	48
242	BOOKING_CREATED	You've booked East Side Meeting Room 6 from 2025-05-15 12:00 to 2025-05-15 13:00	t	2025-04-21 12:50:24.590976+01	2025-04-21 12:50:25.040133+01	120	43
258	BOOKING_CREATED	You've booked East Side Meeting Room 6 from 2025-04-28 14:00 to 2025-04-28 18:00	t	2025-04-21 12:50:24.757549+01	2025-04-21 12:50:25.043602+01	130	42
259	BOOKING_CONFIRMED	Your booking for East Side Meeting Room 6 has been confirmed	t	2025-04-21 12:50:24.768409+01	2025-04-21 12:50:25.052598+01	130	42
279	BOOKING_REMINDER	Reminder: You have a booking for Suburban Mall Event Space 10 starting at 2025-04-23 13:00	t	2025-04-21 12:50:24.860441+01	2025-04-21 12:50:25.063617+01	131	46
225	BOOKING_COMPLETED	Your booking for University Area Meeting Room 7 has been completed	t	2025-04-21 12:50:24.398687+01	2025-04-21 12:50:25.075493+01	110	53
\.


--
-- Data for Name: teams_team; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.teams_team (id, name, leader_id) FROM stdin;
\.


--
-- Data for Name: teams_team_members; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.teams_team_members (id, team_id, user_id) FROM stdin;
\.


--
-- Data for Name: teams_teaminvitation; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.teams_teaminvitation (id, accepted, created_at, recipient_id, sender_id, team_id) FROM stdin;
\.


--
-- Data for Name: users_user; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users_user (id, password, last_login, is_superuser, is_staff, is_active, date_joined, email, phone, user_type, team_leader_id) FROM stdin;
32	pbkdf2_sha256$1000000$J1fzHemWbv0LBqmev4OJ9A$FrGweCR9d8+lHNYf5a9OM3Pw5sLZ14dTLPwMeqkCBdM=	\N	f	f	t	2025-04-21 12:49:36.242606+01	owner1@example.com	555-000-1001	OWNER	\N
33	pbkdf2_sha256$1000000$QkTbvg5EPhUHOf4N7Xfwaz$1pRDA5XbIxXuNNDpzK6B9q8AmnuXagnnqJtbTJlX8I8=	\N	f	f	t	2025-04-21 12:49:37.414814+01	owner2@example.com	555-000-1002	OWNER	\N
34	pbkdf2_sha256$1000000$57wBKTuzQIxpgv49A7UuXX$c3IOmxOTB59CueBqSxLjHgEmf59GpmMrSRkkqzolOEI=	\N	f	f	t	2025-04-21 12:49:38.521946+01	owner3@example.com	555-000-1003	OWNER	\N
35	pbkdf2_sha256$1000000$SINRzvft4LW3ZMqt7Gfls1$K6VheGz3sMWReNsr01WYloaCD6mChH9cqH1iTuF6F/w=	\N	f	f	t	2025-04-21 12:49:41.993479+01	owner4@example.com	555-000-1004	OWNER	\N
36	pbkdf2_sha256$1000000$Dyd60e4XiiEi97runlNmQX$/j6+ZBOmCqjkFV4TxqiwqH47lVWu0b4iFqAcn0EeLhU=	\N	f	f	t	2025-04-21 12:49:44.132722+01	owner5@example.com	555-000-1005	OWNER	\N
37	pbkdf2_sha256$1000000$yRnwCRLH8LyAxekUJEwHAE$CCUgNWxPFZVFgrX5TQEjwWe360kcyggQjOspxRtKr8M=	\N	f	f	t	2025-04-21 12:49:45.613889+01	admin1@example.com	555-001-1001	ADMIN	\N
38	pbkdf2_sha256$1000000$yGE8hRb9qlPggL22yQW6Hi$B2KRLJgAH5jEgf36eUAGijn3bs3ZJRl+DXItsznLX3I=	\N	f	f	t	2025-04-21 12:49:47.053186+01	admin2@example.com	555-001-1002	ADMIN	\N
39	pbkdf2_sha256$1000000$CHsdbL0yCexkBqEZhaaDj7$uhvXaAQz4Tl0u/KK7ak380A/pBDb9fe+3sdwCcuU5+8=	\N	f	f	t	2025-04-21 12:49:48.46242+01	admin3@example.com	555-001-1003	ADMIN	\N
40	pbkdf2_sha256$1000000$Y9uARow7isi9eYWSapGIVo$tRm1w29NQd1+yBUfJMGcWJGOYBowvSoiuu08cIw76Aw=	\N	f	f	t	2025-04-21 12:49:49.673625+01	user1@example.com	555-002-1001	GENERAL	\N
41	pbkdf2_sha256$1000000$szYZFBOjgNi3fICoB1rUDb$8dlQACZt0UiNX+sq+hLkzQTlXO1ea1TiSdSlkJKgfMo=	\N	f	f	t	2025-04-21 12:49:54.253226+01	user2@example.com	555-002-1002	GENERAL	\N
42	pbkdf2_sha256$1000000$enD0FEmq4F0buIJnEwMTO3$rWOMkZ6cDAjSihZ0jMWUy8/eSDyByw76Q7LaH3oNI/4=	\N	f	f	t	2025-04-21 12:49:55.383798+01	user3@example.com	555-002-1003	GENERAL	\N
43	pbkdf2_sha256$1000000$Vuzvg7nGOGsS0MBkWYO5IT$UJhPFlgv/rQG7GK/WUYMR/JyK1FrzIgTXQhlhIdetQQ=	\N	f	f	t	2025-04-21 12:49:56.522366+01	user4@example.com	555-002-1004	GENERAL	\N
44	pbkdf2_sha256$1000000$vVIu9sqoLdEvGlqUdveifi$xg44L3ZHW4SNG2uBcQaB652jz5JH9mWD/GYz478JfcQ=	\N	f	f	t	2025-04-21 12:49:57.695596+01	user5@example.com	555-002-1005	GENERAL	\N
45	pbkdf2_sha256$1000000$7BocZMB4XYLk2KYJLaAW66$82yJYxAcQdOCEzmjKwrHfocu/GtNSruOYzuOePLbs4M=	\N	f	f	t	2025-04-21 12:49:59.565097+01	user6@example.com	555-002-1006	GENERAL	\N
46	pbkdf2_sha256$1000000$tH3l0BxSc9kMeT92e5Bkiq$a2xGoTDU4LPvd0C8iIvdOiN3K2pGyj/eTB0XgdMh9KE=	\N	f	f	t	2025-04-21 12:50:04.377466+01	user7@example.com	555-002-1007	GENERAL	\N
47	pbkdf2_sha256$1000000$QXdjNMGfE9LyWdeYnVwRg4$lybA34NzD3A26EJFPSAbq+qAIJlIb5PYFGT9PRgsP8M=	\N	f	f	t	2025-04-21 12:50:08.346349+01	user8@example.com	555-002-1008	GENERAL	\N
48	pbkdf2_sha256$1000000$q4ZjFn2D9NVkfiNZ1ypbKD$/dRSGnry8Oe6fWM0nuJqsqJgcPjTJrWPbbYGem4o9x0=	\N	f	f	t	2025-04-21 12:50:09.676132+01	user9@example.com	555-002-1009	GENERAL	\N
49	pbkdf2_sha256$1000000$waETAhzI3RZrF4zlsFRfux$jppew7vAzWq4taffO0mgEhcTXscvRcG34O+NlkTmFV0=	\N	f	f	t	2025-04-21 12:50:11.048034+01	user10@example.com	555-002-1010	GENERAL	\N
50	pbkdf2_sha256$1000000$Yp7Uwikn0yhzBMcmMnHzgL$oEAjDwqzr7zMp+d1peKUmfLRRLO/2O4wx8g29w7hdkI=	\N	f	f	t	2025-04-21 12:50:12.472275+01	employee1@example.com	555-003-1001	EMPLOYEE	\N
51	pbkdf2_sha256$1000000$pOaDZI5K4erHmSnmboHgnC$d/doCprdetR0hGtLZwhWrm4UyDNWJyUYuoCzNx1cEg8=	\N	f	f	t	2025-04-21 12:50:13.447935+01	employee2@example.com	555-003-1002	EMPLOYEE	\N
52	pbkdf2_sha256$1000000$Ai4sauPL7DkCXNLR75KMnL$6P+qxt0hGxqLlhwOR5+VI4XQNlSqvRXKWZhq89QXSqI=	\N	f	f	t	2025-04-21 12:50:14.567981+01	employee3@example.com	555-003-1003	EMPLOYEE	\N
53	pbkdf2_sha256$1000000$r3nhosHQKr1tcW5tiI6huQ$ddfmmeEsEvg4jjzpkE0j1HW/3oRFrqJMTkYlDxkkF7s=	\N	f	f	t	2025-04-21 12:50:18.870839+01	employee4@example.com	555-003-1004	EMPLOYEE	\N
54	pbkdf2_sha256$1000000$hHxoX0sO43IoYZJ6gUZjr2$jdDhU5iFxLBHRVXPzmbdQbLmmmJs6n/Djty3s4LtDaU=	\N	f	f	t	2025-04-21 12:50:20.079561+01	employee5@example.com	555-003-1005	EMPLOYEE	\N
55	pbkdf2_sha256$1000000$rWzcE6QRF5vq9bODSDwmRu$glpssB7Eikx/TsFFrRzso8uj7w3zAJ6FUn7ZtVo/+Aw=	\N	f	f	t	2025-04-21 12:50:21.159949+01	employee6@example.com	555-003-1006	EMPLOYEE	\N
56	pbkdf2_sha256$1000000$4lL0DMyRujHV94yp4Wrs4U$vz/cM1cbqG27njhtJ/s1yf6paT58O+i8zgt/7QM3Ptc=	\N	f	f	t	2025-04-21 12:50:22.272874+01	employee7@example.com	555-003-1007	EMPLOYEE	\N
57	pbkdf2_sha256$1000000$Y6LxZ6JuLeGtN61THVVtp7$S78f3F3Zbvu4cJ8+P0bArJmX5e6e5Ro/ddir9eU8MOw=	\N	f	f	t	2025-04-21 13:00:59.363794+01	umarmd123@gmail.com		GENERAL	\N
58	pbkdf2_sha256$1000000$nSZeWw4s0oXI9WK3joTWtU$ZFh0W8uFJXUlp+fp7FdDSmSmwe3++eGCEWVx6d5Voww=	\N	f	f	t	2025-04-21 13:03:56.323819+01	umarmd12345@gmail.com	08023568955	ADMIN	\N
59	pbkdf2_sha256$1000000$7b4pJjHSMwxU4zOZj8i6ze$EQx/SidS6eEDAKWXNgwhezd2tFJgfjzX+ZkJ9yti5TI=	\N	f	f	t	2025-04-22 19:22:54.318324+01	umarmd709@gmail.com		GENERAL	\N
60	pbkdf2_sha256$1000000$We5JGzVW3E2BTcJ9jWbU2U$Gh7LJh+FReL12UITJYkJ2c0OL3FOYbs/nQfwevidtJY=	\N	f	f	t	2025-04-22 19:33:12.236882+01	umarmd234@gmail.com		TEAM_LEADER	\N
61	pbkdf2_sha256$1000000$LUPz6bPQU8iBPkFqCd8Q2o$2tvLmbi2Ou8yal8Ook59dI7cnu7GaRrmJI5SMwdysEQ=	\N	f	f	t	2025-04-22 22:45:57.92535+01	email@email.com		ADMIN	\N
62	pbkdf2_sha256$1000000$NFO4r3vAGVuezP9HRSbYN3$23P7QvdtV/heqEE8MzuC42N5Yfq4gDdmQf8ZpVrIhOc=	\N	f	f	t	2025-04-22 23:28:00.247191+01	umarwalid4055@gmail.com		GENERAL	\N
\.


--
-- Data for Name: users_user_groups; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: users_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: workspaces_amenity; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.workspaces_amenity (id, name, description, icon) FROM stdin;
9	High-Speed WiFi	Fast internet connection	wifi
10	Coffee Machine	Free coffee	coffee
11	Printer	Printing services	print
12	Whiteboard	For brainstorming	edit
13	Monitor	External displays	desktop
14	Standing Desk	Adjustable height desk	table
15	Kitchen Access	Full kitchen facilities	utensils
16	Parking	On-site parking	car
\.


--
-- Data for Name: workspaces_workspace; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.workspaces_workspace (id, name, description, is_available, opening_time, closing_time, location, address, max_capacity, min_capacity, price_per_hour, created_at, updated_at, thumbnail, owner_id, workspace_type_id) FROM stdin;
21	Downtown Event Space 1	A great event space located in Downtown	f	09:00:00	17:00:00	Downtown	485 Main St, Downtown	50	3	97.00	2025-04-21 12:50:23.414186+01	2025-04-21 12:50:23.41421+01		32	9
22	Tech Park Open Desk 2	A great open desk located in Tech Park	f	00:00:00	23:59:00	Tech Park	661 Main St, Tech Park	29	1	43.00	2025-04-21 12:50:23.428214+01	2025-04-21 12:50:23.428227+01		34	7
23	University Area Quiet Zone 3	A great quiet zone located in University Area	f	00:00:00	23:59:00	University Area	300 Main St, University Area	31	2	78.00	2025-04-21 12:50:23.436637+01	2025-04-21 12:50:23.436648+01		34	10
24	Tech Park Quiet Zone 4	A great quiet zone located in Tech Park	t	08:00:00	18:00:00	Tech Park	923 Main St, Tech Park	47	2	58.00	2025-04-21 12:50:23.445474+01	2025-04-21 12:50:23.445485+01		33	10
25	University Area Quiet Zone 5	A great quiet zone located in University Area	t	09:00:00	17:00:00	University Area	702 Main St, University Area	7	4	41.00	2025-04-21 12:50:23.453724+01	2025-04-21 12:50:23.453742+01		34	10
26	East Side Meeting Room 6	A great meeting room located in East Side	t	07:00:00	19:00:00	East Side	934 Main St, East Side	13	4	72.00	2025-04-21 12:50:23.463066+01	2025-04-21 12:50:23.463077+01		33	8
27	University Area Meeting Room 7	A great meeting room located in University Area	f	00:00:00	23:59:00	University Area	172 Main St, University Area	18	1	79.00	2025-04-21 12:50:23.472301+01	2025-04-21 12:50:23.472318+01		33	8
28	Tech Park Private Office 8	A great private office located in Tech Park	t	00:00:00	23:59:00	Tech Park	432 Main St, Tech Park	47	4	44.00	2025-04-21 12:50:23.479932+01	2025-04-21 12:50:23.479974+01		32	6
29	University Area Meeting Room 9	A great meeting room located in University Area	t	07:00:00	19:00:00	University Area	562 Main St, University Area	38	4	20.00	2025-04-21 12:50:23.490161+01	2025-04-21 12:50:23.490175+01		35	8
30	Suburban Mall Event Space 10	A great event space located in Suburban Mall	t	08:00:00	18:00:00	Suburban Mall	469 Main St, Suburban Mall	37	1	72.00	2025-04-21 12:50:23.498477+01	2025-04-21 12:50:23.498494+01		34	9
31	Suburban Mall Event Space 11	A great event space located in Suburban Mall	t	00:00:00	23:59:00	Suburban Mall	255 Main St, Suburban Mall	11	3	71.00	2025-04-21 12:50:23.505844+01	2025-04-21 12:50:23.505861+01		36	9
32	East Side Quiet Zone 12	A great quiet zone located in East Side	t	00:00:00	23:59:00	East Side	878 Main St, East Side	41	3	59.00	2025-04-21 12:50:23.515518+01	2025-04-21 12:50:23.515535+01		34	10
33	Suburban Mall Quiet Zone 13	A great quiet zone located in Suburban Mall	t	00:00:00	23:59:00	Suburban Mall	678 Main St, Suburban Mall	32	2	66.00	2025-04-21 12:50:23.524965+01	2025-04-21 12:50:23.524977+01		35	10
34	Downtown Meeting Room 14	A great meeting room located in Downtown	f	09:00:00	17:00:00	Downtown	892 Main St, Downtown	29	2	64.00	2025-04-21 12:50:23.533319+01	2025-04-21 12:50:23.53333+01		35	8
35	Tech Park Open Desk 15	A great open desk located in Tech Park	t	00:00:00	23:59:00	Tech Park	174 Main St, Tech Park	7	4	83.00	2025-04-21 12:50:23.543296+01	2025-04-21 12:50:23.54331+01		36	7
36	West End Quiet Zone 16	A great quiet zone located in West End	t	00:00:00	23:59:00	West End	313 Main St, West End	9	3	21.00	2025-04-21 12:50:23.549683+01	2025-04-21 12:50:23.549699+01		33	10
37	Suburban Mall Private Office 17	A great private office located in Suburban Mall	t	09:00:00	17:00:00	Suburban Mall	405 Main St, Suburban Mall	44	3	16.00	2025-04-21 12:50:23.560611+01	2025-04-21 12:50:23.560622+01		34	6
38	Tech Park Private Office 18	A great private office located in Tech Park	t	00:00:00	23:59:00	Tech Park	641 Main St, Tech Park	33	3	70.00	2025-04-21 12:50:23.567362+01	2025-04-21 12:50:23.567372+01		34	6
39	West End Quiet Zone 19	A great quiet zone located in West End	t	09:00:00	17:00:00	West End	814 Main St, West End	20	1	23.00	2025-04-21 12:50:23.577903+01	2025-04-21 12:50:23.577912+01		32	10
40	Downtown Open Desk 20	A great open desk located in Downtown	t	00:00:00	23:59:00	Downtown	813 Main St, Downtown	26	2	45.00	2025-04-21 12:50:23.583453+01	2025-04-21 12:50:23.583466+01		32	7
\.


--
-- Data for Name: workspaces_workspace_amenities; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.workspaces_workspace_amenities (id, workspace_id, amenity_id) FROM stdin;
99	21	10
100	21	11
101	21	13
102	21	14
103	21	16
104	22	9
105	22	10
106	22	11
107	22	12
108	22	14
109	22	15
110	23	9
111	23	11
112	23	12
113	23	14
114	23	15
115	23	16
116	24	9
117	24	10
118	24	11
119	24	12
120	24	13
121	24	14
122	24	15
123	24	16
124	25	9
125	25	10
126	25	11
127	25	12
128	25	13
129	25	14
130	25	15
131	25	16
132	26	10
133	26	11
134	26	12
135	26	13
136	26	14
137	26	16
138	27	10
139	27	12
140	27	15
141	28	9
142	28	10
143	28	11
144	28	12
145	28	13
146	28	15
147	28	16
148	29	9
149	29	10
150	29	11
151	29	12
152	29	13
153	29	14
154	29	15
155	29	16
156	30	9
157	30	12
158	30	13
159	30	14
160	30	15
161	30	16
162	31	16
163	31	12
164	31	13
165	31	14
166	32	9
167	32	10
168	32	12
169	32	13
170	32	14
171	32	16
172	33	9
173	33	11
174	33	13
175	33	14
176	33	15
177	33	16
178	34	12
179	34	13
180	35	13
181	35	15
182	36	9
183	36	11
184	36	13
185	37	16
186	37	13
187	37	14
188	38	9
189	38	10
190	38	11
191	38	13
192	38	15
193	38	16
194	39	10
195	39	12
196	39	13
197	39	14
198	39	15
199	39	16
200	40	9
201	40	11
202	40	12
203	40	13
204	40	14
205	40	15
206	40	16
\.


--
-- Data for Name: workspaces_workspacetype; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.workspaces_workspacetype (id, name, description) FROM stdin;
6	Private Office	Fully enclosed private workspace
7	Open Desk	Hot desk in open area
8	Meeting Room	Conference room for meetings
9	Event Space	Large space for events
10	Quiet Zone	Silent working area
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 64, true);


--
-- Name: bookings_booking_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.bookings_booking_id_seq', 138, true);


--
-- Name: bookings_teaminvitation_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.bookings_teaminvitation_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 16, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 32, true);


--
-- Name: notifications_notification_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.notifications_notification_id_seq', 285, true);


--
-- Name: teams_team_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.teams_team_id_seq', 1, false);


--
-- Name: teams_team_members_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.teams_team_members_id_seq', 1, false);


--
-- Name: teams_teaminvitation_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.teams_teaminvitation_id_seq', 1, false);


--
-- Name: users_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_user_groups_id_seq', 1, false);


--
-- Name: users_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_user_id_seq', 62, true);


--
-- Name: users_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_user_user_permissions_id_seq', 1, false);


--
-- Name: workspaces_amenity_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.workspaces_amenity_id_seq', 16, true);


--
-- Name: workspaces_workspace_amenities_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.workspaces_workspace_amenities_id_seq', 206, true);


--
-- Name: workspaces_workspace_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.workspaces_workspace_id_seq', 40, true);


--
-- Name: workspaces_workspacetype_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.workspaces_workspacetype_id_seq', 10, true);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: authtoken_token authtoken_token_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_pkey PRIMARY KEY (key);


--
-- Name: authtoken_token authtoken_token_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_user_id_key UNIQUE (user_id);


--
-- Name: bookings_booking bookings_booking_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bookings_booking
    ADD CONSTRAINT bookings_booking_pkey PRIMARY KEY (id);


--
-- Name: bookings_teaminvitation bookings_teaminvitation_leader_id_invitee_id_d5e53b8d_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bookings_teaminvitation
    ADD CONSTRAINT bookings_teaminvitation_leader_id_invitee_id_d5e53b8d_uniq UNIQUE (leader_id, invitee_id);


--
-- Name: bookings_teaminvitation bookings_teaminvitation_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bookings_teaminvitation
    ADD CONSTRAINT bookings_teaminvitation_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: notifications_notification notifications_notification_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notifications_notification
    ADD CONSTRAINT notifications_notification_pkey PRIMARY KEY (id);


--
-- Name: teams_team_members teams_team_members_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.teams_team_members
    ADD CONSTRAINT teams_team_members_pkey PRIMARY KEY (id);


--
-- Name: teams_team_members teams_team_members_team_id_user_id_7b6a61ef_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.teams_team_members
    ADD CONSTRAINT teams_team_members_team_id_user_id_7b6a61ef_uniq UNIQUE (team_id, user_id);


--
-- Name: teams_team teams_team_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.teams_team
    ADD CONSTRAINT teams_team_pkey PRIMARY KEY (id);


--
-- Name: teams_teaminvitation teams_teaminvitation_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.teams_teaminvitation
    ADD CONSTRAINT teams_teaminvitation_pkey PRIMARY KEY (id);


--
-- Name: teams_teaminvitation teams_teaminvitation_team_id_recipient_id_396be649_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.teams_teaminvitation
    ADD CONSTRAINT teams_teaminvitation_team_id_recipient_id_396be649_uniq UNIQUE (team_id, recipient_id);


--
-- Name: users_user users_user_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user
    ADD CONSTRAINT users_user_email_key UNIQUE (email);


--
-- Name: users_user_groups users_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user_groups
    ADD CONSTRAINT users_user_groups_pkey PRIMARY KEY (id);


--
-- Name: users_user_groups users_user_groups_user_id_group_id_b88eab82_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user_groups
    ADD CONSTRAINT users_user_groups_user_id_group_id_b88eab82_uniq UNIQUE (user_id, group_id);


--
-- Name: users_user users_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user
    ADD CONSTRAINT users_user_pkey PRIMARY KEY (id);


--
-- Name: users_user_user_permissions users_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user_user_permissions
    ADD CONSTRAINT users_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: users_user_user_permissions users_user_user_permissions_user_id_permission_id_43338c45_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user_user_permissions
    ADD CONSTRAINT users_user_user_permissions_user_id_permission_id_43338c45_uniq UNIQUE (user_id, permission_id);


--
-- Name: workspaces_amenity workspaces_amenity_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.workspaces_amenity
    ADD CONSTRAINT workspaces_amenity_pkey PRIMARY KEY (id);


--
-- Name: workspaces_workspace_amenities workspaces_workspace_ame_workspace_id_amenity_id_2cf13b1f_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.workspaces_workspace_amenities
    ADD CONSTRAINT workspaces_workspace_ame_workspace_id_amenity_id_2cf13b1f_uniq UNIQUE (workspace_id, amenity_id);


--
-- Name: workspaces_workspace_amenities workspaces_workspace_amenities_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.workspaces_workspace_amenities
    ADD CONSTRAINT workspaces_workspace_amenities_pkey PRIMARY KEY (id);


--
-- Name: workspaces_workspace workspaces_workspace_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.workspaces_workspace
    ADD CONSTRAINT workspaces_workspace_pkey PRIMARY KEY (id);


--
-- Name: workspaces_workspacetype workspaces_workspacetype_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.workspaces_workspacetype
    ADD CONSTRAINT workspaces_workspacetype_pkey PRIMARY KEY (id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: authtoken_token_key_10f0b77e_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX authtoken_token_key_10f0b77e_like ON public.authtoken_token USING btree (key varchar_pattern_ops);


--
-- Name: bookings_bo_user_id_7b21ce_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX bookings_bo_user_id_7b21ce_idx ON public.bookings_booking USING btree (user_id, start_time);


--
-- Name: bookings_bo_workspa_7bff13_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX bookings_bo_workspa_7bff13_idx ON public.bookings_booking USING btree (workspace_id, start_time, end_time);


--
-- Name: bookings_booking_booked_by_id_bc075bad; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX bookings_booking_booked_by_id_bc075bad ON public.bookings_booking USING btree (booked_by_id);


--
-- Name: bookings_booking_user_id_834dfc23; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX bookings_booking_user_id_834dfc23 ON public.bookings_booking USING btree (user_id);


--
-- Name: bookings_booking_workspace_id_cd8e29bb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX bookings_booking_workspace_id_cd8e29bb ON public.bookings_booking USING btree (workspace_id);


--
-- Name: bookings_teaminvitation_invitee_id_71ff14b7; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX bookings_teaminvitation_invitee_id_71ff14b7 ON public.bookings_teaminvitation USING btree (invitee_id);


--
-- Name: bookings_teaminvitation_leader_id_e1a125cb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX bookings_teaminvitation_leader_id_e1a125cb ON public.bookings_teaminvitation USING btree (leader_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: notificatio_booking_42bffa_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX notificatio_booking_42bffa_idx ON public.notifications_notification USING btree (booking_id, notification_type);


--
-- Name: notificatio_user_id_427e4b_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX notificatio_user_id_427e4b_idx ON public.notifications_notification USING btree (user_id, is_read);


--
-- Name: notifications_notification_booking_id_6e796c4c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX notifications_notification_booking_id_6e796c4c ON public.notifications_notification USING btree (booking_id);


--
-- Name: notifications_notification_user_id_b5e8c0ff; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX notifications_notification_user_id_b5e8c0ff ON public.notifications_notification USING btree (user_id);


--
-- Name: teams_team_leader_id_3ad12e5b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX teams_team_leader_id_3ad12e5b ON public.teams_team USING btree (leader_id);


--
-- Name: teams_team_members_team_id_ebb2d47d; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX teams_team_members_team_id_ebb2d47d ON public.teams_team_members USING btree (team_id);


--
-- Name: teams_team_members_user_id_d2b52fb4; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX teams_team_members_user_id_d2b52fb4 ON public.teams_team_members USING btree (user_id);


--
-- Name: teams_teaminvitation_recipient_id_06dd097b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX teams_teaminvitation_recipient_id_06dd097b ON public.teams_teaminvitation USING btree (recipient_id);


--
-- Name: teams_teaminvitation_sender_id_73166819; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX teams_teaminvitation_sender_id_73166819 ON public.teams_teaminvitation USING btree (sender_id);


--
-- Name: teams_teaminvitation_team_id_99a770e2; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX teams_teaminvitation_team_id_99a770e2 ON public.teams_teaminvitation USING btree (team_id);


--
-- Name: users_user_email_243f6e77_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_user_email_243f6e77_like ON public.users_user USING btree (email varchar_pattern_ops);


--
-- Name: users_user_groups_group_id_9afc8d0e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_user_groups_group_id_9afc8d0e ON public.users_user_groups USING btree (group_id);


--
-- Name: users_user_groups_user_id_5f6f5a90; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_user_groups_user_id_5f6f5a90 ON public.users_user_groups USING btree (user_id);


--
-- Name: users_user_team_leader_id_9666999b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_user_team_leader_id_9666999b ON public.users_user USING btree (team_leader_id);


--
-- Name: users_user_user_permissions_permission_id_0b93982e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_user_user_permissions_permission_id_0b93982e ON public.users_user_user_permissions USING btree (permission_id);


--
-- Name: users_user_user_permissions_user_id_20aca447; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_user_user_permissions_user_id_20aca447 ON public.users_user_user_permissions USING btree (user_id);


--
-- Name: workspaces_workspace_amenities_amenity_id_e431dbb4; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX workspaces_workspace_amenities_amenity_id_e431dbb4 ON public.workspaces_workspace_amenities USING btree (amenity_id);


--
-- Name: workspaces_workspace_amenities_workspace_id_21564dc4; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX workspaces_workspace_amenities_workspace_id_21564dc4 ON public.workspaces_workspace_amenities USING btree (workspace_id);


--
-- Name: workspaces_workspace_owner_id_d8b120c0; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX workspaces_workspace_owner_id_d8b120c0 ON public.workspaces_workspace USING btree (owner_id);


--
-- Name: workspaces_workspace_workspace_type_id_ba5ca454; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX workspaces_workspace_workspace_type_id_ba5ca454 ON public.workspaces_workspace USING btree (workspace_type_id);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: authtoken_token authtoken_token_user_id_35299eff_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_user_id_35299eff_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: bookings_booking bookings_booking_booked_by_id_bc075bad_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bookings_booking
    ADD CONSTRAINT bookings_booking_booked_by_id_bc075bad_fk_users_user_id FOREIGN KEY (booked_by_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: bookings_booking bookings_booking_user_id_834dfc23_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bookings_booking
    ADD CONSTRAINT bookings_booking_user_id_834dfc23_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: bookings_booking bookings_booking_workspace_id_cd8e29bb_fk_workspace; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bookings_booking
    ADD CONSTRAINT bookings_booking_workspace_id_cd8e29bb_fk_workspace FOREIGN KEY (workspace_id) REFERENCES public.workspaces_workspace(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: bookings_teaminvitation bookings_teaminvitation_invitee_id_71ff14b7_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bookings_teaminvitation
    ADD CONSTRAINT bookings_teaminvitation_invitee_id_71ff14b7_fk_users_user_id FOREIGN KEY (invitee_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: bookings_teaminvitation bookings_teaminvitation_leader_id_e1a125cb_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bookings_teaminvitation
    ADD CONSTRAINT bookings_teaminvitation_leader_id_e1a125cb_fk_users_user_id FOREIGN KEY (leader_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: notifications_notification notifications_notifi_booking_id_6e796c4c_fk_bookings_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notifications_notification
    ADD CONSTRAINT notifications_notifi_booking_id_6e796c4c_fk_bookings_ FOREIGN KEY (booking_id) REFERENCES public.bookings_booking(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: notifications_notification notifications_notification_user_id_b5e8c0ff_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notifications_notification
    ADD CONSTRAINT notifications_notification_user_id_b5e8c0ff_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: teams_team teams_team_leader_id_3ad12e5b_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.teams_team
    ADD CONSTRAINT teams_team_leader_id_3ad12e5b_fk_users_user_id FOREIGN KEY (leader_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: teams_team_members teams_team_members_team_id_ebb2d47d_fk_teams_team_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.teams_team_members
    ADD CONSTRAINT teams_team_members_team_id_ebb2d47d_fk_teams_team_id FOREIGN KEY (team_id) REFERENCES public.teams_team(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: teams_team_members teams_team_members_user_id_d2b52fb4_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.teams_team_members
    ADD CONSTRAINT teams_team_members_user_id_d2b52fb4_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: teams_teaminvitation teams_teaminvitation_recipient_id_06dd097b_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.teams_teaminvitation
    ADD CONSTRAINT teams_teaminvitation_recipient_id_06dd097b_fk_users_user_id FOREIGN KEY (recipient_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: teams_teaminvitation teams_teaminvitation_sender_id_73166819_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.teams_teaminvitation
    ADD CONSTRAINT teams_teaminvitation_sender_id_73166819_fk_users_user_id FOREIGN KEY (sender_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: teams_teaminvitation teams_teaminvitation_team_id_99a770e2_fk_teams_team_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.teams_teaminvitation
    ADD CONSTRAINT teams_teaminvitation_team_id_99a770e2_fk_teams_team_id FOREIGN KEY (team_id) REFERENCES public.teams_team(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_groups users_user_groups_group_id_9afc8d0e_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user_groups
    ADD CONSTRAINT users_user_groups_group_id_9afc8d0e_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_groups users_user_groups_user_id_5f6f5a90_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user_groups
    ADD CONSTRAINT users_user_groups_user_id_5f6f5a90_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user users_user_team_leader_id_9666999b_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user
    ADD CONSTRAINT users_user_team_leader_id_9666999b_fk_users_user_id FOREIGN KEY (team_leader_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_user_permissions users_user_user_perm_permission_id_0b93982e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user_user_permissions
    ADD CONSTRAINT users_user_user_perm_permission_id_0b93982e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_user_permissions users_user_user_permissions_user_id_20aca447_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user_user_permissions
    ADD CONSTRAINT users_user_user_permissions_user_id_20aca447_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: workspaces_workspace_amenities workspaces_workspace_amenity_id_e431dbb4_fk_workspace; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.workspaces_workspace_amenities
    ADD CONSTRAINT workspaces_workspace_amenity_id_e431dbb4_fk_workspace FOREIGN KEY (amenity_id) REFERENCES public.workspaces_amenity(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: workspaces_workspace workspaces_workspace_owner_id_d8b120c0_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.workspaces_workspace
    ADD CONSTRAINT workspaces_workspace_owner_id_d8b120c0_fk_users_user_id FOREIGN KEY (owner_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: workspaces_workspace_amenities workspaces_workspace_workspace_id_21564dc4_fk_workspace; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.workspaces_workspace_amenities
    ADD CONSTRAINT workspaces_workspace_workspace_id_21564dc4_fk_workspace FOREIGN KEY (workspace_id) REFERENCES public.workspaces_workspace(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: workspaces_workspace workspaces_workspace_workspace_type_id_ba5ca454_fk_workspace; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.workspaces_workspace
    ADD CONSTRAINT workspaces_workspace_workspace_type_id_ba5ca454_fk_workspace FOREIGN KEY (workspace_type_id) REFERENCES public.workspaces_workspacetype(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

